import type { Metadata } from "next"
import { Chakra_Petch } from "next/font/google"
import "./globals.css"
import { NavbarContextProvider } from "@/contexts/useNavbar"
// import { FooterContextProvider } from "@/contexts/useFooter"

const chakraPetch = Chakra_Petch({
  subsets: ["thai"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "2nd Phone App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${chakraPetch.className} min-h-screen antialiased`}>
        {/* <FooterContextProvider> */}
        <NavbarContextProvider>{children}</NavbarContextProvider>
        {/* </FooterContextProvider> */}
      </body>
    </html>
  )
}
